# https://bun.com/docs/runtime/bunfig

[install]
exact = true
# frozenLockfile = true

minimumReleaseAge = 259200 # seconds
# minimumReleaseAgeExcludes = ["typescript"]

[install.lockfile]
save = true

[install.security]
# run `bun add -d @acme/bun-security-scanner` to install the scanner
scanner = "@acme/bun-security-scanner"
